const profiles = [
    {
      id: '1',
      image: require('../assets/girl8.jpg'),
      name: 'Jessica Parker',
      age: 23,
      occupation: 'Professional model',
      distance: '8 km',
      location: 'Chicago, IL',
    },
    {
      id: '2',
      image: require('../assets/girl3.jpg'),
      name: 'Emily Watson',
      age: 25,
      occupation: 'Graphic Designer',
      distance: '3 km',
      location: 'Chicago, IL',
    },
    {
      id: '3',
      image: require('../assets/girl7.jpg'),
      name: 'Sophia Lee',
      age: 22,
      occupation: 'Software Engineer',
      distance: '5 km',
      location: 'Chicago, IL',
    },
    {
      id: '4',
      image: require('../assets/girl4.jpg'),
      name: 'Mia Johnson',
      age: 24,
      occupation: 'Marketing Specialist',
      distance: '6 km',
      location: 'Chicago, IL',
    },
    {
      id: '5',
      image: require('../assets/girl5.jpg'),
      name: 'Olivia Brown',
      age: 26,
      occupation: 'Photographer',
      distance: '1 km',
      location: 'Chicago, IL',
    },
    {
      id: '6',
      image: require('../assets/girl6.jpg'),
      name: 'Ava Davis',
      age: 21,
      occupation: 'Student',
      distance: '3 km',
      location: 'Chicago, IL',
    },
    {
      id: '7',
      image: require('../assets/girl2.jpg'),
      name: 'Isabella Martinez',
      age: 27,
      occupation: 'Interior Designer',
      distance: '6 km',
      location: 'Chicago, IL',
    },
    {
      id: '8',
      image: require('../assets/girl1.jpg'),
      name: 'Ella Thompson',
      age: 23,
      occupation: 'Journalist',
      distance: '2 km',
      location: 'Chicago, IL',
    },
  ];
  
  export default profiles;
  